import Head from 'next/head'

import Main from '../components/Main'
import About from '../components/About'
import Contact from '../components/Contact'




export default function Home() {
  return (
    <div>
      <Head>
        <title>Carol Chimirri | Advogada</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/../logo.png" />
      </Head>
    
 
    <Main />
    <About />
    <Contact />
    

    </div>
  )
}
